const {
	VITE_API_BASE_URL,
	VITE_NANOID_CHARSET,
	VITE_NANOID_SIZE,
	VITE_HOSTED_SERVER,
	VITE_PUBLIC_VAPID_KEY,
} = import.meta.env;

const BASE_API = VITE_API_BASE_URL;
const NANOID_CHARSET = VITE_NANOID_CHARSET;
const NANOID_SIZE = VITE_NANOID_SIZE;
const HOSTED_SERVER = VITE_HOSTED_SERVER || undefined;
const PUBLIC_VAPID_KEY = VITE_PUBLIC_VAPID_KEY;

export {
	BASE_API,
	NANOID_CHARSET,
	NANOID_SIZE,
	HOSTED_SERVER,
	PUBLIC_VAPID_KEY,
};
