const {
	VITE_API_BASE_URL,
	VITE_NANOID_CHARSET,
	VITE_NANOID_SIZE,
	VITE_HOSTED_SERVER,
	VITE_PUBLIC_VAPID_KEY,
	VITE_API_IMG_URL,
	VITE_IS_ADMIN,
	MODE,
} = import.meta.env;

const BASE_API = VITE_API_BASE_URL;
const NANOID_CHARSET = VITE_NANOID_CHARSET;
const NANOID_SIZE = VITE_NANOID_SIZE;
const HOSTED_SERVER = VITE_HOSTED_SERVER || undefined;
const PUBLIC_VAPID_KEY = VITE_PUBLIC_VAPID_KEY;
const API_IMG_URL = VITE_API_IMG_URL;
const IS_ADMIN = VITE_IS_ADMIN;
const IS_PRODUCTION = MODE === 'production';

export {
	API_IMG_URL,
	BASE_API,
	HOSTED_SERVER,
	IS_ADMIN,
	IS_PRODUCTION,
	NANOID_CHARSET,
	NANOID_SIZE,
	PUBLIC_VAPID_KEY,
};
