const {
	VITE_API_BASE_URL,
	VITE_NANOID_CHARSET,
	VITE_NANOID_SIZE,
	VITE_HOSTED_SERVER,
} = import.meta.env;

const BASE_API = VITE_API_BASE_URL;
const NANOID_CHARSET = VITE_NANOID_CHARSET;
const NANOID_SIZE = VITE_NANOID_SIZE;
const HOSTED_SERVER = VITE_HOSTED_SERVER || undefined;

export { BASE_API, NANOID_CHARSET, NANOID_SIZE, HOSTED_SERVER };
